defaults:
  - dataset: toy
  - model: mlp
  - train: default
  - experiment: baseline

project_name: "thesis-mode-connectivity"
run_name: "debug"
seed: 0

hydra:
  run:
    dir: .
  sweep:
    dir: .
    subdir: ${hydra.job.num}
  output_subdir: null  # Disable .hydra subdirectory creation
