defaults: []

experiment_name: "garipov_vgg16_curve_init_alpha0.9"

output_root: "results/vgg16/cifar10/curves/initialization/biased_linear/alpha_0.9/checkpoints"

# Endpoints
endpoint0: "results/vgg16/cifar10/endpoints/standard/seed0/checkpoints/checkpoint-200.pt"
endpoint1: "results/vgg16/cifar10/endpoints/standard/seed1/checkpoints/checkpoint-200.pt"

dataset: "CIFAR10"
data_path: "./data"
transform: "VGG"
model: "VGG16"

# Curve parameters
curve: "Bezier"
num_bends: 3

# Training
epochs: 150
save_intermediate: true
save_freq: 150
lr: 0.015
wd: 0.0  # NO REGULARIZATION
seed: 1

# Initialization parameters
init_method: "biased"
init_alpha: 0.9  # Very close to end endpoint

use_test: true
use_wandb: true
project_name: "thesis-mode-connectivity"
