defaults: []

experiment_name: "garipov_vgg16_curve_neuronswap_mid2_reg"

output_root: "results/vgg16/cifar10/curves/neuronswap/mid2_reg/checkpoints"

# Endpoints
endpoint0: "results/vgg16/cifar10/endpoints/standard/seed0/checkpoints/checkpoint-200.pt"
endpoint1: "results/vgg16/cifar10/endpoints/neuronswap/mid2/checkpoints/checkpoint-200.pt"

dataset: "CIFAR10"
data_path: "./data"
transform: "VGG"
model: "VGG16"

# Curve parameters
curve: "Bezier"
num_bends: 3

# Training
epochs: 30
save_intermediate: true
save_freq: 30
lr: 0.01
wd: 5e-4
seed: 1    # Random seed (default from dnn-mode-connectivity)

use_test: true
use_wandb: true
project_name: "thesis-mode-connectivity"
